### ISSUE TITLE
Support LiveView or TiShadow

### ISSUE THREAD

**Issue by HazemKhaled** [TheSmiths/ti.es6#10]
Add support for --liveview or --shadow

**Comment by KtorZ** [comment]
Nope. The plugin isn't maintained anymore. And since the alloy cli is likely to be rebuilt from scratch (or has been,  I am not following it anymore), it will partially break the plugin and I don't feel like to dive into alloy source again to find out what to do. 
Sorry :/ 
If you're still interested in the project, fell free to fork it and to keep it up-to-date.
